import type { Metadata } from "next";
import Sidebar from "../(components)/sidebar";
import {
  Book,
  Home,
  Layers,
  Paperclip,
  Shield,
  StickyNote,
  Users,
} from "lucide-react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const SIDEBAR_ITEMS = [
  {
    label: "Dashboard",
    href: "/institute/dashboard",
    icon: <Home className="size-5" />,
  },
  {
    label: "Students",
    href: "/institute/students",
    icon: <Users className="size-5" />,
  },
  {
    label: "Prev Papers",
    href: "/institute/prev-papers",
    icon: <StickyNote className="size-5" />,
  },
  {
    label: "Syllabus",
    href: "/institute/syllabus",
    icon: <Layers className="size-5" />,
  },
  {
    label: "Notes",
    href: "/institute/notes",
    icon: <Book className="size-5" />,
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Sidebar items={SIDEBAR_ITEMS} />
        <div className="p-4 sm:ml-64">{children}</div>
      </body>
    </html>
  );
}
