import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider
        publishableKey={
          "pk_test_bGliZXJhbC1tb29zZS00Mi5jbGVyay5hY2NvdW50cy5kZXYk"
        }
      >
        <body className={inter.className}>{children}</body>
      </ClerkProvider>
    </html>
  );
}
